export const initialNotifications = [
  {
    id: 1,
    color: "primary",
    avatarColor: "!bg-primary",
    icon: "ti-gift",
    text1: "Your Order Has Been Shipped",
    text2: "Order No: 123456 Has Shipped To YourDelivery Address",
    class: "",
    class1: "",
  },
  {
    id: 2,
    color: "secondary",
    avatarColor: "bg-secondary",
    icon: "ti-discount-2",
    text1: "Discount Available",
    text2: "Discount Available On Selected Products",
    class: "",
    class1: "",
  },
  {
    id: 3,
    color: "pink",
    avatarColor: "bg-pink",
    icon: "ti-user-check",
    text1: "Account Has Been Verified",
    text2: "Your Account Has Been Verified Successfully",
    class: "",
    class1: "",
  },
  {
    id: 4,
    color: "warning",
    avatarColor: "bg-warning",
    icon: "ti-circle-check",
    text1: "Order Placed ",
    text2: "Order Placed Successflly",
    class: "text-warning",
    class1: " ID:1116773",
  },
  {
    id: 5,
    color: "success",
    avatarColor: "bg-success",
    icon: "ti-clock",
    text1: "Order Delayed",
    text2: "Order Delayed Unfortunately",
    class: "text-success",
    class1: " ID:7731116",
  },
];
