import avatar1 from "@assets/images/profile/avatar1.jpeg";
import avatar2 from "@assets/images/profile/avatar2.jpeg";
import avatar3 from "@assets/images/profile/avatar3.jpeg";
import avatar4 from "@assets/images/profile/avatar4.jpeg";
import avatar5 from "@assets/images/profile/avatar5.jpeg";
import avatar6 from "@assets/images/profile/avatar6.jpeg";
import avatar7 from "@assets/images/profile/avatar7.jpeg";
import avatar8 from "@assets/images/profile/avatar8.jpeg";
import avatar9 from "@assets/images/profile/avatar9.jpeg";
import avatar10 from "@assets/images/profile/avatar10.jpeg";
import { ChatData } from "@type/types";

export const chats: ChatData[] = [
  {
    id: 1,
    name: "Miles",
    avatar: avatar1,
    status: "online",
    lastMessage: "Hello",
    lastMessageTime: "1:04PM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar1,
        sender: "Miles",
        content: "Hi there! How can I assist you today?",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content:
          "I accidentally deleted some important files. Can they be recovered?",
        time: "11:34 AM",
        type: "sent",
      },
      {
        avatar: avatar1,
        sender: "Miles",
        content:
          "I'm sorry to hear that. Let me guide you through the process to resolve it. Could you please provide your username?",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "No thank you",
        time: "11:37 AM",
        type: "sent",
      },
      {
        avatar: avatar1,
        sender: "Miles",
        content:
          "I'm sorry to hear that. Let me guide you through the process to resolve it. Could you please provide your username?",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "No thank you",
        time: "11:37 AM",
        type: "sent",
      },
      {
        avatar: avatar1,
        sender: "Miles",
        content:
          "I'm sorry to hear that. Let me guide you through the process to resolve it. Could you please provide your username?",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: " Could you please provide your username?",
        time: "11:37 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 2,
    name: "Laverne Grady",
    avatar: avatar2,
    status: "offline",
    lastMessage: "Good morning",
    lastMessageTime: "1:04PM",
    lastMessageStatus: "#45556E",
    isOnline: true,
    messages: [
      {
        avatar: avatar2,
        sender: "Alice",
        content: "Hello world",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar2,
        sender: "Alice",
        content: "What up's",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Im fine",
        time: "11:34 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 3,
    name: "Bessie",
    avatar: avatar3,
    status: "online",
    lastMessage: "Good morning",
    lastMessageTime: "1:04PM",
    lastMessageStatus: "#01D2B4",
    isOnline: false,
    messages: [
      {
        avatar: avatar3,
        sender: "Alice",
        content: "Hello world",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "Alice",
        content: "What up's",
        time: "11:32 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Im fine",
        time: "11:34 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 4,
    name: "Dwight Moore",
    avatar: avatar4,
    status: "online",
    lastMessage: "Hey there!",
    lastMessageTime: "12:30 PM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar4,
        sender: "Alice",
        content: "Hello! How can I help you?",
        time: "12:00 PM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "I need assistance with my account.",
        time: "12:05 PM",
        type: "sent",
      },
      {
        avatar: avatar4,
        sender: "Alice",
        content: "Sure, could you please provide your username?",
        time: "12:10 PM",
        type: "received",
      },
    ],
  },
  {
    id: 5,
    name: "Beth Balistreri",
    avatar: avatar5,
    status: "offline",
    lastMessage: "Good morning!",
    lastMessageTime: "9:30 AM",
    lastMessageStatus: "#45556E",
    isOnline: false,
    messages: [
      {
        avatar: avatar5,
        sender: "Alice",
        content: "Hey!",
        time: "9:00 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Morning! How are you?",
        time: "9:05 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 6,
    name: "Josephine Kuhic",
    avatar: avatar6,
    status: "online",
    lastMessage: "Hi!",
    lastMessageTime: "11:45 AM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar6,
        sender: "Olivia",
        content: "Hello there!",
        time: "11:30 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Hi Olivia!",
        time: "11:35 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 7,
    name: "Vandervort",
    avatar: avatar7,
    status: "offline",
    lastMessage: "Hey!",
    lastMessageTime: "10:15 AM",
    lastMessageStatus: "#45556E",
    isOnline: false,
    messages: [
      {
        avatar: avatar7,
        sender: "Alice",
        content: "Good morning!",
        time: "10:00 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Morning Daniel!",
        time: "10:05 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 8,
    name: "Alice Ritchie",
    avatar: avatar8,
    status: "online",
    lastMessage: "Hello!",
    lastMessageTime: "2:00 PM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar8,
        sender: "Sophia",
        content: "Hi! How are you?",
        time: "1:45 PM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "I'm doing well, thanks!",
        time: "1:50 PM",
        type: "sent",
      },
    ],
  },
  {
    id: 9,
    name: "Armando Kihn",
    avatar: avatar9,
    status: "offline",
    lastMessage: "Hey!",
    lastMessageTime: "8:30 AM",
    lastMessageStatus: "#45556E",
    isOnline: false,
    messages: [
      {
        avatar: avatar9,
        sender: "Alice",
        content: "Good morning!",
        time: "8:00 AM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Morning Liam!",
        time: "8:05 AM",
        type: "sent",
      },
    ],
  },
  {
    id: 10,
    name: "Marilyn Langosh",
    avatar: avatar10,
    status: "online",
    lastMessage: "Hello!",
    lastMessageTime: "3:30 PM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar10,
        sender: "Emma",
        content: "Hi there!",
        time: "3:15 PM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Hello Emma!",
        time: "3:20 PM",
        type: "sent",
      },
    ],
  },
  {
    id: 11,
    name: "Marilyn Langosh",
    avatar: avatar2,
    status: "online",
    lastMessage: "Hello!",
    lastMessageTime: "3:30 PM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar10,
        sender: "Emma",
        content: "Hi there!",
        time: "3:15 PM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Hello Emma!",
        time: "3:20 PM",
        type: "sent",
      },
    ],
  },
  {
    id: 12,
    name: "Marilyn Langosh",
    avatar: avatar4,
    status: "online",
    lastMessage: "Hello!",
    lastMessageTime: "3:30 PM",
    lastMessageStatus: "#01D2B4",
    isOnline: true,
    messages: [
      {
        avatar: avatar10,
        sender: "Emma",
        content: "Hi there!",
        time: "3:15 PM",
        type: "received",
      },
      {
        avatar: avatar3,
        sender: "You",
        content: "Hello Emma!",
        time: "3:20 PM",
        type: "sent",
      },
    ],
  },
];
